export interface pokemonInfos {
  abilities: any,
  base_experience: any,
  forms: any,
  game_indices: any,
  held_items: any,
  id: any,
  is_default: any,
  location_area_encounters: any,
  moves: any,
  name: any,
  order: any,
  species: any,
  sprites: any,
  stats: any,
  types: any,
  weight: any,
}